name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

permissions:
  contents: write

env:
  COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run lint
      - name: build
        run: npm run build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Check dist content
        run: ls -l dist

      - name: Check installed modules
        run: ls -l node_modules

      - name: Start server in background
        run: npm run preview &

      - name: Run Playwright tests
        run: npm run test:e2e

      - name: get screenshots
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshot
          path: screenshot.png

      - name: Notify failure to Discord
        uses: sarisia/actions-status-discord@v1.15.3
        if: ${{ failure() }}
        with:
          title: "failure in Pokedex pipeline"
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          description: Pokedex problem during pipeline !
          username: GitHub Actions
          url: "https://github.com/ericvanm/full-stack-open-pokedex"
      - name: Upload Playwright report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Trigger deployment render
        if: ${{ github.event_name == 'push' && ! contains(env.COMMIT_MESSAGES, '#skip') }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      - name: Notify success to Discord
        uses: sarisia/actions-status-discord@v1.15.3
        if: ${{ success() && github.event_name == 'push' && ! contains(env.COMMIT_MESSAGES, '#skip') }}
        with:
          title: "deploy Anecdotes"
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          description: New version of Anecdotes deployed !
          username: GitHub Actions
          url: "https://github.com/ericvanm/full-stack-open-pokedex"
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && ! contains(env.COMMIT_MESSAGES, '#skip') }}
        uses: anothrNick/github-tag-action@1.73.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      - name: Notify success to Discord
        if: ${{ success() && github.event_name == 'push' && ! contains(env.COMMIT_MESSAGES, '#skip') }}
        uses: rjstone/discord-webhook-notify@v2.1.1
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: info
          details: New tag created for Anecdotes version
